!!com.snobot.simulator.config.v1.SimulatorConfigV1
mAccelerometers: []
mAnalogIn: []
mAnalogOut: []
mDefaultI2CWrappers: {}
mDefaultSpiWrappers: {}
mDigitalIO: []
mEncoders:
- mConnectedSpeedControllerHandle: 120
  mHandle: 120
  mName: CAN Encoder (20)
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim$CtreEncoder
- mConnectedSpeedControllerHandle: 121
  mHandle: 121
  mName: CAN Encoder (21)
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim$CtreEncoder
- mConnectedSpeedControllerHandle: 122
  mHandle: 122
  mName: CAN Encoder (22)
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim$CtreEncoder
mGyros: []
mPwm:
- mHandle: 120
  mMotorModelConfig:
    mGearReduction: 100.0
    mGearboxEfficiency: 1.0
    mHasBrake: true
    mInverted: false
    mMotorType: 775 Pro
    mNumMotors: 1
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.RotationalLoadMotorSimulationConfig
    mArmCenterOfMass: 0.0
    mArmMass: 0.0
    mConstantAssistTorque: 0.0
    mOverCenterAssistTorque: 0.0
  mName: rotationMotor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 121
  mMotorModelConfig:
    mGearReduction: 100.0
    mGearboxEfficiency: 1.0
    mHasBrake: true
    mInverted: false
    mMotorType: 775 Pro
    mNumMotors: 1
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.RotationalLoadMotorSimulationConfig
    mArmCenterOfMass: 0.0
    mArmMass: 0.0
    mConstantAssistTorque: 0.0
    mOverCenterAssistTorque: 0.0
  mName: extensionMotor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
- mHandle: 122
  mMotorModelConfig:
    mGearReduction: 100.0
    mGearboxEfficiency: 1.0
    mHasBrake: true
    mInverted: false
    mMotorType: 775 Pro
    mNumMotors: 1
  mMotorSimConfig: !!com.snobot.simulator.motor_sim.RotationalLoadMotorSimulationConfig
    mArmCenterOfMass: 0.0
    mArmMass: 0.0
    mConstantAssistTorque: 0.0
    mOverCenterAssistTorque: 0.0
  mName: wristMotor
  mType: com.snobot.simulator.simulator_components.ctre.CtreTalonSrxSpeedControllerSim
mRelays: []
mSimulatorComponents: []
mSolenoids: []
